export const GET_STOPS = 'GET_STOPS';
export const ADD_STOP = 'ADD_STOP';
export const DELETE_STOP = 'DELETE_STOP'
export const STOPS_ERROR = 'STOPS_ERROR'

export const GET_CHILDREN = 'GET_CHILDREN'
export const ADD_CHILD = 'ADD_CHILD';
export const UPDATE_CHILD_CHECKBOX = 'UPDATE_CHILD_CHECKBOX';
export const UNCHECK_ALL_CHILDREN = 'UNCHECK_ALL_CHILDREN';
export const DELETE_CHILD = 'DELETE_CHILD'
export const CHILDREN_ERROR = 'CHILDREN_ERROR'

export const GET_SCHOOLS = 'GET_SCHOOLS'
export const ADD_SCHOOL = 'ADD_SCHOOL';
export const DELETE_SCHOOL = 'DELETE_SCHOOL'
export const SCHOOLS_ERROR = 'SCHOOLS_ERROR'